export const capitals = {
  Afghanistan: "Kabul",
  Albania: "Tirana",
  Algeria: "Algiers",
  Andorra: "Andorra la Vella",
  Angola: "	Luanda",
  "Antigua and Barbuda": "Saint John's",
  Argentina: "Buenos Aires",
  Armenia: "Yerevan",
  Australia: "Canberra",
  Austria: "Vienna",
  Azerbaijan: "Baku",
  Bahamas: "Nassau",
  Bahrain: "Manama",
  Bangladesh: "Dhaka",
  Barbados: "Bridgetown",
  Belarus: "Minsk",
  Belgium: "Brussels",
  Belize: "Belmopan",
  Benin: "Porto Novo",
  Bhutan: "Thimphu",
  Bolivia: "La Paz",
  "Bosnia and Herzegovina": "Sarajevo",
  Botswana: "Gaborone",
  Brazil: "Brasilia",
  Brunei: "Bandar Seri Begawan",
  Bulgaria: "Sofia",
  "Burkina Faso": "Ouagadougou",
  Burundi: "Gitega",
  Cambodia: "Phnom Penh",
  Cameroon: "Yaounde",
  Canada: "Ottawa",
  "Cape Verde": "Praia",
  "Central African Republic": "Bangui",
  Chad: "N'Djamena",
  Chile: "Santiago",
  China: "Beijing",
  Colombia: "Bogota",
  Comoros: "Moroni",
  "Democratic Republic of the Congo": "Kinshasa",
  "Republic of the Congo": "Brazzaville",
  "Costa Rica": "San Jose",
  "Côte d'Ivoire": "Yamoussoukro",
  Croatia: "Zagreb",
  Cuba: "Havana",
  Cyprus: "Nicosia",
  "Czech Republic": "Prague",
  Denmark: "Copenhagen",
  Djibouti: "Djibouti",
  Dominica: "Roseau",
  "Dominican Republic": "Santo Domingo",
  "East Timor": "	Dili",
  Ecuador: "Quito",
  Egypt: "Cairo",
  "El Salvador": "San Salvador",
  "United Kingdom": "London",
  "Equatorial Guinea": "Malabo",
  Eritrea: "Asmara",
  Estonia: "Tallinn",
  Eswatini: "Mbabana",
  Ethiopia: "Addis Ababa",
  "Federated States of Micronesia": "Palikir",
  Fiji: "Suva",
  Finland: "Helsinki",
  France: "Paris",
  Gabon: "Libreville",
  Gambia: "Banjul",
  Georgia: "Tbilisi",
  Germany: "Berlin",
  Ghana: "Accra",
  Greece: "Athens",
  Grenada: "Saint George's",
  Guatemala: "Guatemala City",
  Guinea: "Conakry",
  "Guinea-Bissau": "Bissau",
  Guyana: "Georgetown",
  Haiti: "Port au Prince",
  Honduras: "Tegucigalpa",
  Hungary: "Budapest",
  Iceland: "Reykjavik",
  India: "	New Delhi",
  Indonesia: "Jakarta",
  Iran: "Tehran",
  Iraq: "Baghdad",
  Ireland: "Dublin",
  Israel: "Jerusalem",
  Italy: "Rome",
  Jamaica: "Kingston",
  Japan: "Tokyo",
  Jordan: "Amman",
  Kazakhstan: "Nur-Sultan",
  Kenya: "Nairobi",
  Kiribati: "Tarawa Atoll",
  Kosovo: "Pristina",
  Kuwait: "Kuwait City",
  Kyrgyzstan: "Bishkek",
  Laos: "Vientiane",
  Latvia: "Riga",
  Lebanon: "Beirut",
  Lesotho: "Maseru",
  Liberia: "Monrovia",
  Libya: "Tripoli",
  Liechtenstein: "Vaduz",
  Lithuania: "Vilnius",
  Luxembourg: "Luxembourg",
  Madagascar: "Antananarivo",
  Malawi: "Lilongwe",
  Malaysia: "Kuala Lumpur",
  Maldives: "Male",
  Mali: "Bamako",
  Malta: "Valletta",
  "Marshall Islands": "Majuro",
  Mauritania: "Nouakchott",
  Mauritius: "Port Louis",
  Mexico: "Mexico City",
  Moldova: "Chisinau",
  Monaco: "Monaco",
  Mongolia: "Ulaanbaatar",
  Montenegro: "Podgorica",
  Morocco: "Rabat",
  Mozambique: "Maputo",
  Myanmar: "Nay Pyi Taw",
  Namibia: "Windhoek",
  Nauru: "No capital",
  Nepal: "Kathmandu",
  Netherlands: "Amsterdam",
  "New Zealand": "Wellington",
  Nicaragua: "Managua",
  Niger: "Niamey",
  Nigeria: "Lagos",
  "North Korea": "Pyongyang",
  "North Macedonia": "Skopje",
  Norway: "Oslo",
  Oman: "Muscat",
  Pakistan: "Islamabad",
  Palau: "Melekeok",
  Palestine: "Jerusalem",
  Panama: "Panama City",
  "Papua New Guinea": "Port Moresby",
  Paraguay: "Asuncion",
  Peru: "Lima",
  Philippines: "Manila",
  Poland: "Warsaw",
  Portugal: "Lisbon",
  Qatar: "Doha",
  Romania: "Bucharest",
  Russia: "Moscow",
  Rwanda: "Kigali",
  "Saint Kitts and Nevis": "Basseterre",
  "Saint Lucia": "Castries",
  "Saint Vincent and the Grenadines": "Kingstown",
  Samoa: "Apia",
  "San Marino": "San Marino",
  "Sao Tome and Principe": "Sao Tome",
  "Saudi Arabia": "Riyadh",
  Senegal: "Dakar",
  Serbia: "Belgrade",
  Seychelles: "Victoria",
  "Sierra Leone": "Freetown",
  Singapore: "Singapore",
  Slovakia: "Bratislava",
  Slovenia: "Ljubljana",
  "Solomon Islands": "Honiara",
  Somalia: "Mogadishu",
  "South Africa": "Pretoria",
  "South Korea": "Seoul",
  "South Sudan": "Juba",
  Spain: "Madrid",
  "Sri Lanka": "Sri Jayawardenapura Kotte",
  Sudan: "Khartoum",
  Suriname: "Paramaribo",
  Sweden: "Stockholm",
  Switzerland: "Bern",
  Syria: "Damascus",
  Taiwan: "Taipei",
  Tajikistan: "Dushanbe",
  Tanzania: "Dodoma",
  Thailand: "Bangkok",
  Togo: "Lome",
  Tonga: "Nuku'alofa",
  "Trinidad and Tobago": "Port of Spain",
  Tunisia: "Tunis",
  Türkiye: "Ankara",
  Turkmenistan: "Ashgabat",
  Tuvalu: "Funafuti",
  Uganda: "Kampala",
  Ukraine: "Kyiv",
  "United Arab Emirates": "Abu Dhabi",
  "United States": "Washington D.C.",
  Uruguay: "Montevideo",
  Uzbekistan: "Tashkent",
  Vanuatu: "Port Vila",
  "Vatican City": "Vatican City",
  Venezuela: "Caracas",
  Vietnam: "Hanoi",
  Yemen: "Sana'a",
  Zambia: "Lusaka",
  Zimbabwe: "Harare",
};

export const cities = [
  "Herat",
  "Rana",
  "Shkoder",
  "Oran",
  "Kouba",
  "Llorts",
  "Benguela",
  "Namibe",
  "Woods",
  "Salta",
  "Rio Grande",
  "San Francisco",
  "Sydney",
  "Adelaide",
  "Melbourne",
  "Brisbane",
  "Salzbourg",
  "Graz",
  "Quba",
  "Xirdalan",
  "Chittagong",
  "Uttara",
  "Rockley",
  "White Hill",
  "Homiel",
  "Antwerp",
  "Bruges",
  "Sucre",
  "Cochabamba",
  "Zenica",
  "Francistown",
  "Sao Paulo",
  "Rio de Janeiro",
  "Borovan",
  "Topoli",
  "Sihanoukville",
  "Calgary",
  "Vancouver",
  "Toronto",
  "Montreal",
  "Durrës",
  "Huambo",
  "Cordoba",
  "Gyumri",
  "Freeport",
  "Riffa",
  "Speightstown",
  "Gomel",
  "San Ignacio",
  "Abomey-Calavi",
  "Phuntsholing",
  "El Alto",
  "Banja Luka",
  "Kuala Belait",
  "Plovdiv",
  "Bobo-Dioulasso",
  "Muyinga",
  "Siem Reap",
  "Mindelo",
  "Cotonou",
  "Bujumbura",
  "Douala",
  "Bimbo",
  "Moundou",
  "Puente Alto",
  "Shanghai",
  "Medellin",
  "Lubumbashi",
  "Pointe-Noire",
  "Alajuela",
  "Abidjan",
  "Bouake",
  "Split",
  "Limassol",
  "Brno",
  "Ostrava",
  "Aarhus",
  "Ali Sabieh",
  "Portsmouth",
  "Dare",
  "Guayaquil",
  "Alexandria",
  "Sanata Ana",
  "Bata",
  "Keren",
  "Tartu",
  "Manzini",
  "Dire Dawa",
  "Nasinu",
  "Espoo",
  "Tampere",
  "Marseille",
  "Lyon",
  "Port-Gentil",
  "Serekunda",
  "Batumi",
  "Hamburg",
  "Kumasi",
  "Thessaloniki",
  "Gouyave",
  "Nzerekore",
  "Gabu",
  "Linden",
  "Gonaives",
  "San Pedro Sula",
  "Debrecen",
  "Kopavogur",
  "Mumbai",
  "Surabaya",
  "Mashhad",
  "Basra",
  "Cork",
  "Tel Aviv",
  "Milan",
  "Spanish Town",
  "Osaka",
  "Zarqa",
  "Almaty",
  "Mombasa",
  "Bairiki",
  "Hamhung",
  "Busan",
  "Prizren",
  "Al Jahra",
  "Osh",
  "Pakxe",
  "Daugavpils",
  "Tripoli",
  "Teyateyaneng",
  "Gbarnga",
  "Benghazi",
  "Schaan",
  "Kaunas",
  "Toamasina",
  "Blantyre",
  "George Town",
  "Addu City",
  "Sikasso",
  "Ebeye",
  "Nouadhibou",
  "Weno",
  "Tiraspol",
  "Darkhan",
  "Niksic",
  "Casablanca",
  "Matola",
  "Yangon",
  "Rundu",
  "Denigomudu",
  "Pokhara",
  "Rotterdam",
  "We",
  "Auckland",
  "Leon",
  "Abuja",
  "Bitola",
  "Bergen",
  "Salalah",
  "Lahore",
  "Airai",
  "Colon",
  "Lae",
  "Ciudad del Este",
  "Arequipa",
  "Quezon City",
  "Krakow",
  "Porto",
  "Al Rayyan",
  "Constanta",
  "Saint-Petersburg",
  "Muhanga",
  "Charlestown",
  "Vaitele",
  "Trinidade",
  "Jeddah",
  "Touba",
  "Novi Sad",
  "Anse Etoile",
  "Bo",
  "Kosice",
  "Maribor",
  "Gizo",
  "Hargeisa",
  "Yei",
  "Barcelona",
  "Colombo",
  "Port Sudan",
  "Lelydorp",
  "Gothenburg",
  "Geneva",
  "Aleppo",
  "New Taipei",
  "Mwanza",
  "Pak Kret",
  "Sokode",
  "Neiafu",
  "San Fernando",
  "Sfax",
  "Istanbul",
  "Asau",
  "Gulu",
  "Donetsk",
  "Dubai",
  "Birmingham",
  "Los Angeles",
  "Maldonado",
  "Namangan",
  "Luganville",
  "Maracaibo",
  "Aden",
  "Kitwe",
  "Bulawayo",
];
